//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InchikDiplomchik.ApplicatModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Hiistoryy = new HashSet<Hiistoryy>();
            this.Order = new HashSet<Order>();
        }
    
        public int ID_employee { get; set; }
        public string FIO { get; set; }
        public string Pasport { get; set; }
        public string Adress { get; set; }
        public string Telephon { get; set; }
        public string Email { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int Id_post { get; set; }
        public string INN { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int Id_statusJob { get; set; }
    
        public virtual ArhivStatusEmp ArhivStatusEmp { get; set; }
        public virtual Post Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hiistoryy> Hiistoryy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }

        public string POIUYTRE
        {
            get
            {
                return Post.NamePost.ToString();
            }

        }
        public int KOLZAk
        {
            get
            {
                return Order.Count;
            }
        }
    }
}
