//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InchikDiplomchik.ApplicatModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiplomchikEntities : DbContext
    {
        private static DiplomchikEntities _context;
        public DiplomchikEntities()
            : base("name=DiplomchikEntities")
        {
        }
        public static DiplomchikEntities GetContext()
        {
            if (_context == null)
                _context = new DiplomchikEntities();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArhivStatusEmp> ArhivStatusEmp { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<ClientType> ClientType { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<DISCOUN> DISCOUN { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Hiistoryy> Hiistoryy { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<orderStatus> orderStatus { get; set; }
        public virtual DbSet<PaymentStatus> PaymentStatus { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Stages> Stages { get; set; }
        public virtual DbSet<StagesDevelopment> StagesDevelopment { get; set; }
        public virtual DbSet<StatusHistory> StatusHistory { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
